version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: npm install dependencies
          command: |
            npm install --save
            npm update --save

  build_docker_image:
    docker:
      - image: circleci/node
    steps: 
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker Image
          command: |
            docker build -t nodejsatanuapp1 -t atanu/nodejsatanuapp1:latest .
            echo $DOCKER_PASSWORD | docker login -u atanubiswas --password-stdin
            docker push atanubiswas/nodejsatanuapp1:latest

workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image

### test1